#!/usr/bin/env bash
set -euo pipefail

# Run linting step (ruff). Usage: lint.sh [--no-fix]
FIX=true
for arg in "$@"; do
  case "$arg" in
    --no-fix)
      FIX=false
      ;;
    -h|--help)
      echo "Usage: $0 [--no-fix]"
      exit 0
      ;;
    *)
      echo "Unknown argument: $arg"
      echo "Usage: $0 [--no-fix]"
      exit 1
      ;;
  esac
done

if [ ! -x ".venv/bin/python" ]; then
  echo "Virtualenv Python not found at .venv/bin/python. Create venv first."
  exit 1
fi
PY=.venv/bin/python
TMP_OUTPUT="$(mktemp)"
if [ "$FIX" = true ]; then
  echo "Running ruff --fix ."
  if "$PY" -m ruff check . --fix 2>&1 | tee "$TMP_OUTPUT"; then
    rm -f "$TMP_OUTPUT"
  else
    echo "ruff reported issues. Inspecting output in $TMP_OUTPUT"
    # Generate structured lesson candidate for human review
    head -n 200 "$TMP_OUTPUT" > ".github/skills/run-checks/_snippet.tmp"
    cat > ".github/skills/run-checks/last_lesson.md" <<'MD'
# Lesson candidate (generated by lint.sh)

- tool: ruff
- summary: Ruff reported one or more issues; see snippet below.

---

```
$(cat .github/skills/run-checks/_snippet.tmp)
```

Suggested action: Review the snippet above and, if valid, add a short
lesson to `.github/copilot-instructions.md` under "Run-checks lessons"
(maintainer approval required).
MD
    rm -f ".github/skills/run-checks/_snippet.tmp"
    exit 1
  fi
else
  echo "Running ruff check ."
  if "$PY" -m ruff check . 2>&1 | tee "$TMP_OUTPUT"; then
    rm -f "$TMP_OUTPUT"
  else
    echo "ruff reported issues. Inspecting output in $TMP_OUTPUT"
    # Generate a structured lesson candidate for human review
    head -n 200 "$TMP_OUTPUT" > ".github/skills/run-checks/_snippet.tmp"
    cat > ".github/skills/run-checks/last_lesson.md" <<'MD'
# Lesson candidate (generated by lint.sh)

- tool: ruff
- summary: Ruff reported one or more issues; see snippet below.

---

```
$(cat .github/skills/run-checks/_snippet.tmp)
```

Suggested action: Review the snippet above and, if valid, add a short
lesson to `.github/copilot-instructions.md` under "Run-checks lessons"
(maintainer approval required).
MD
    rm -f ".github/skills/run-checks/_snippet.tmp"
    exit 1
  fi
fi
