#!/usr/bin/env bash
set -euo pipefail

# Run tests (pytest). Usage: test.sh
if [ ! -x ".venv/bin/python" ]; then
  echo "Virtualenv Python not found at .venv/bin/python. Create venv first."
  exit 1
fi
PY=.venv/bin/python

TMP_OUTPUT="$(mktemp)"
echo "Running pytest -q"
if "$PY" -m pytest -q 2>&1 | tee "$TMP_OUTPUT"; then
  rm -f "$TMP_OUTPUT"
else
  echo "pytest failures detected. Inspecting output in $TMP_OUTPUT"
  # Generate structured lesson candidate for human review
  head -n 400 "$TMP_OUTPUT" > ".github/skills/run-checks/_snippet.tmp"
  cat > ".github/skills/run-checks/last_lesson.md" <<'MD'
# Lesson candidate (generated by test.sh)

- tool: pytest
- summary: Tests failed; see snippet below (first 400 lines).

---

```
$(cat .github/skills/run-checks/_snippet.tmp)
```

Suggested action: Review the snippet above and, if valid, add a short
lesson to `.github/copilot-instructions.md` under "Run-checks lessons"
(maintainer approval required).
MD
  rm -f ".github/skills/run-checks/_snippet.tmp"
  exit 1
fi
