name: Run checks (matrix)
on:
  pull_request:
    branches: [ "dev" ]
  push:
    branches: [ "dev" ]

jobs:
  run_checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        db: [sqlite, postgres]
        python-version: [3.11]
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: pyledger
        ports:
          - 5432:5432
        options: >-
          --health-cmd 'pg_isready -U postgres' --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-py-${{ matrix.python-version }}-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: pip-${{ runner.os }}-py-${{ matrix.python-version }}-

      - name: Cache mypy cache
        uses: actions/cache@v4
        with:
          path: .mypy_cache
          key: mypy-${{ runner.os }}-py-${{ matrix.python-version }}-${{ hashFiles('**/*.py') }}
          restore-keys: mypy-${{ runner.os }}-py-${{ matrix.python-version }}-

      - name: Install dependencies
        run: |
          python -m venv .venv
          .venv/bin/python -m pip install --upgrade pip
          .venv/bin/python -m pip install -r requirements.dev.txt

      - name: Configure DB env
        run: |
          if [ "${{ matrix.db }}" = "postgres" ]; then
            echo "DATABASE_URL=postgresql://postgres:postgres@postgres:5432/pyledger" >> $GITHUB_ENV
            echo "CI_DB=postgres" >> $GITHUB_ENV
          else
            echo "DATABASE_URL=sqlite+aiosqlite:///:memory:" >> $GITHUB_ENV
            echo "CI_DB=sqlite" >> $GITHUB_ENV
          fi

      - name: Wait for Postgres
        if: matrix.db == 'postgres'
        run: |
          # Simple wait loop that exits non-zero on timeout
          .venv/bin/python - <<'PY'
          import sys, time, socket
          host='postgres'; port=5432
          for _ in range(30):
              try:
                  s=socket.create_connection((host,port),2); s.close(); print('postgres ready'); sys.exit(0)
              except Exception:
                  time.sleep(1)
          print('timed out'); sys.exit(1)
          PY

      - name: Run canonical checks
        run: |
          ./.github/skills/run-checks/run_checks.sh --no-fix
